models:
  - model_name: RandomForestClassifier
    best_parameters:
      n_estimators: 100
      max_depth: 10
      min_samples_split: 2
      min_samples_leaf: 1
      criterion: [gini,entropy]

  - model_name: LogisticRegression
    best_parameters:
      #penalty: l2
      #C: 1.0
      solver: [lbfgs,sag,liblinear]
      #max_iter: 1000

  - model_name: GradientBoostingClassifier
    best_parameters:
      n_estimators: 100
      learning_rate: [0.1,0.05]
     # max_depth: 3
