models:
  - name: RandomForestClassifier
    parameters:
      #n_estimators: 100
      max_depth: [10,5]
      min_samples_split: [2,3]
      #min_samples_leaf: 1
      criterion: [gini,entropy]

  - name: LogisticRegression
    parameters:
      #penalty: l2
      C: [1.0,0.5]
      solver: [lbfgs,sag,liblinear]
      #max_iter: 1000

  - name: GradientBoostingClassifier
    parameters:
      #n_estimators: 100
      learning_rate: [0.1,0.05]
      max_depth: [3,5]
