models:
  - name: RandomForestRegressor
    parameters:
      n_estimators: [100,200]
      max_depth: [10,8]
      #min_samples_split: 2
      #min_samples_leaf: 1
      
  - name: GradientBoostingRegressor
    parameters:
      #n_estimators: 100
      learning_rate: [0.1 , 0.3]
      #max_depth: 3
      #loss: ls
      
  - name: SVR
    parameters:
      kernel: ['rbf','linear']
      #C: 1.0
      #epsilon: 0.1

  - name: Ridge
    parameters:
       alpha: [0.05,0.1]
       
