Best Model:
  Model_name: RandomForestRegressor
  Model_score: 0.6702363623907625
  Pickle_Location: C:\Users\Lokesh\Desktop\Algerian_forest_fire_data_2023\MODEL_CONTAINER_REGRESSION\2023-22-09_19-42-10\RandomForestRegressor.pkl
  best_model_parameters: &id001
    max_depth: 10
    min_samples_leaf: 1
    n_estimators: 200
Model22_09_19_44_18_:
  Model_name: RandomForestRegressor
  Model_score: 0.6702363623907625
  Pickle_Location: C:\Users\Lokesh\Desktop\Algerian_forest_fire_data_2023\MODEL_CONTAINER_REGRESSION\2023-22-09_19-42-10\RandomForestRegressor.pkl
  best_model_parameters: *id001
Model22_09_19_47_13_:
  Model_name: GradientBoostingRegressor
  Model_score: 0.6647910718671577
  Pickle_Location: C:\Users\Lokesh\Desktop\Algerian_forest_fire_data_2023\MODEL_CONTAINER_REGRESSION\2023-22-09_19-45-06\GradientBoostingRegressor.pkl
  best_model_parameters:
    learning_rate: 0.1
    n_estimators: 200
Model22_09_19_49_22_:
  Model_name: GradientBoostingRegressor
  Model_score: 0.6679085365563396
  Pickle_Location: C:\Users\Lokesh\Desktop\Algerian_forest_fire_data_2023\MODEL_CONTAINER_REGRESSION\2023-22-09_19-47-16\GradientBoostingRegressor.pkl
  best_model_parameters:
    learning_rate: 0.1
    n_estimators: 200
